import express from 'express';
import { exec } from 'child_process';
import { Client } from '@notionhq/client';
import fs from 'fs';
import path from 'path';

const app = express();
app.use(express.json());

// ── Config ────────────────────────────────────────────────────────────────────
const NOTION_TOKEN = process.env.NOTION_TOKEN;
const OUTPUT_DIR   = process.env.OUTPUT_DIR || `${process.env.HOME}/claude-builds`;
const PORT         = process.env.PORT || 3456;
const CLAUDE_BIN   = process.env.CLAUDE_BIN || 'claude';

if (!NOTION_TOKEN) {
  console.error('❌  NOTION_TOKEN is required');
  process.exit(1);
}

const notion = new Client({ auth: NOTION_TOKEN });

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Recursively extract plain text from all block types */
function blocksToText(blocks) {
  return blocks
    .map(block => {
      const type = block.type;
      const content = block[type];
      if (!content) return '';

      // Rich text nodes (paragraph, heading_*, bulleted_list_item, etc.)
      if (content.rich_text) {
        return content.rich_text.map(t => t.plain_text).join('');
      }
      return '';
    })
    .filter(Boolean)
    .join('\n');
}

/** Slugify a string for use as a directory name */
function slugify(str) {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 80);
}

/** Pull the plain-text title from a Notion page */
function getTitle(page) {
  const titleProp = Object.values(page.properties || {}).find(
    p => p.type === 'title'
  );
  return titleProp?.title?.[0]?.plain_text || page.id;
}

// ── Webhook handler ───────────────────────────────────────────────────────────
app.post('/notion-webhook', async (req, res) => {
  // Acknowledge immediately so Notion doesn't retry
  res.sendStatus(200);

  try {
    const pageId = req.body?.data?.id;
    if (!pageId) {
      console.warn('⚠️  Webhook received but no page ID found in payload');
      return;
    }

    console.log(`\n📥  Received webhook for page: ${pageId}`);

    // Fetch page metadata + blocks
    const [page, blocksResponse] = await Promise.all([
      notion.pages.retrieve({ page_id: pageId }),
      notion.blocks.children.list({ block_id: pageId, page_size: 100 }),
    ]);

    const title       = getTitle(page);
    const description = blocksToText(blocksResponse.results);

    if (!description.trim()) {
      console.warn(`⚠️  Page "${title}" has no description — skipping`);
      return;
    }

    // Create output directory
    const slug       = slugify(title);
    const projectDir = path.join(OUTPUT_DIR, slug);
    fs.mkdirSync(projectDir, { recursive: true });

    // Write a human-readable brief alongside the build
    const brief = [
      `# ${title}`,
      '',
      `> Auto-generated by notion-claude-webhook on ${new Date().toISOString()}`,
      `> Notion page: https://www.notion.so/${pageId.replace(/-/g, '')}`,
      '',
      '## Description',
      '',
      description,
    ].join('\n');

    fs.writeFileSync(path.join(projectDir, 'BRIEF.md'), brief);

    // Build the prompt
    const prompt = [
      `You are an expert software engineer. Build the following feature completely and autonomously.`,
      `Output all source files to the current working directory.`,
      `Create a README.md summarising what was built and how to run it.`,
      ``,
      `## Feature: ${title}`,
      ``,
      description,
    ].join('\n');

    console.log(`🏗️   Building "${title}" → ${projectDir}`);

    // Run Claude Code
    const safePrompt = prompt.replace(/"/g, '\\"').replace(/`/g, '\\`');
    const cmd = `cd "${projectDir}" && ${CLAUDE_BIN} --print "${safePrompt}"`;

    exec(cmd, { env: { ...process.env }, maxBuffer: 10 * 1024 * 1024 }, (err, stdout, stderr) => {
      if (err) {
        console.error(`❌  Claude Code failed for "${title}":`, stderr);
      } else {
        console.log(`✅  Build complete for "${title}"\n`, stdout.slice(0, 500));
      }
    });

  } catch (err) {
    console.error('❌  Error processing webhook:', err.message);
  }
});

// ── Health check ──────────────────────────────────────────────────────────────
app.get('/health', (_req, res) => res.json({ ok: true, ts: new Date().toISOString() }));

app.listen(PORT, () => {
  console.log(`\n🚀  notion-claude-webhook listening on :${PORT}`);
  console.log(`    Output dir : ${OUTPUT_DIR}`);
  console.log(`    Claude bin : ${CLAUDE_BIN}`);
});
